### ISSUE TITLE
Returns multiple records for some ZCTAs

### ISSUE THREAD

**Issue by chriszs** [theonaunheim/surgeo#10]
Appears to be those that cross state lines. Examples: 69201, 51360, 59270

**Comment by theonaunheim** [comment]
Good call out--thanks.

I'm adding the following line to fetch_geography.ipynb ...

`df = df.groupby(df.index).apply(sum)`

... which should sum the files on an index (zcta) basis prior to processing. Will run overnight and see what shakes out.

**Comment by theonaunheim** [comment]
@chriszs 
When you have a moment would you please update to version 1.0.2, check whether this works on your machine, and close this out if fixed?

Thanks again for catching this--much appreciated.

**Comment by chriszs** [comment]
Looks good! Thank you!
